### ISSUE TITLE
Asterisk Server Disconnects

### ISSUE THREAD

**Issue by diablo581** [TECH7Fox/asterisk-hass-integration#63]
I'm having trouble where the integration goes into a disconnected state and doesn't recover.  When I try to reload the config in an automation it says that the entity can't be reloaded because it isn't in a recoverable state.

If a restart HA then it recovers.

**Comment by TECH7Fox** [comment]
Yeah, the integration doesn't have recover set up.
There is a new library that I want to use, so when the connection get's lost, the library reconnects.

See #57

**Comment by wolfwander** [comment]
What about de ability to reload de integration?
It would be very useful for connection issues.

**Comment by TECH7Fox** [comment]
Can you try [v0.9.5](https://github.com/TECH7Fox/asterisk-hass-integration/releases/tag/v0.9.5)? On setup it should retry if it fails to connect, so that the add-on has time to start up on a full system restart. It probably doesn't work when the integration is already set up and the add-on restarts.

**Comment by TECH7Fox** [comment]
> What about de ability to reload de integration?

It looks like it's only possible to retry on setup. There isn't a way to fully reload the integration after all the entities are set up.

**Comment by TECH7Fox** [comment]
Closing now since the integration now retries on startup, and if it disconnects after startup you can now reload it manually without restarting HA. Let me know if you have any issues.
